import express from "express";
import { dbConnection } from "./dataBases/dbConnection.js";
import userRouter from "./src/modules/users/user.router.js";
const app = express();
const port = 3000;
dbConnection();
app.use(express.json());
app.use("/users", userRouter);
app.get("/", (req, res) => res.send("Hello World!"));
app.listen(port, () => console.log(`Example app listening on port ${port}!`));
